# Generated by Django 3.0.4 on 2020-04-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenmodel',
            old_name='publisged_on',
            new_name='published_on',
        ),
    ]
