# Generated by Django 3.0.4 on 2020-04-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapings', '0004_citizenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenmodel',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citizenmodel',
            name='spider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citizenmodel',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
