# Generated by Django 3.0.4 on 2020-04-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapings', '0005_auto_20200402_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenmodel',
            options={'verbose_name': 'Citizen Articles', 'verbose_name_plural': 'Citizen Articles'},
        ),
    ]
